### ISSUE TITLE
Blurry resume

### ISSUE THREAD

**Issue by ziadevcom** [drkostas/vscode-portfolio#1]
Hi, I was looking at your portfolio and really liked the idea of vscode as portfolio.

I LOVED it!

On your about page, your pdf is very blurry. Here is a screenshot: 
![image](https://user-images.githubusercontent.com/45315917/233495981-2887c7e7-95a4-4644-8369-1b9e644afb70.png)

Thought, I should let you know.

**Comment by drkostas** [comment]
@ziadevcom let me know if the issue is not fixed

**Comment by ziadevcom** [comment]
Yup, it's fixed.
